name: Build, Test, and Deploy

on:
  push:
    branches:
      - development
      - staging
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
    
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
    
      - name: Install Dependencies
        run: npm install
        working-directory: server
    
      - name: Build Application
        run: npm run build
        working-directory: server
    
      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: server/build

 


  deploy-production:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/production'

    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          name: build-artifacts
          path: server/build

      - name: Deploy to Production
        run: |
          # Add production deployment script here
          echo "Deploying to production..."
